In [1]:
import numpy as np

## Numpy Array

In [8]:
List = [20 , 30 ,40]

In [9]:
np.array(List)

array([20, 30, 40])

In [10]:
matrixList = [[10 , 20 , 30] , [20 , 30 , 40] , [50 , 60 , 70]]

In [12]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [50, 60, 70]])

## arange

In [18]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

## zeros & ones

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [26]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## random

In [45]:
x = np.random.randn(8)

In [46]:
np.random.randint(1,100)

23

In [47]:
np.random.randint(1,100,5)

array([88, 47, 11, 42, 16])

## numpy dizi methodları

In [48]:
x.reshape(2,4)

array([[-0.2158141 ,  0.65537316, -0.00081212,  0.40231958],
       [-0.63618141, -0.19806222, -0.71500005, -0.02877695]])

In [49]:
x.max()

0.6553731556774338

In [50]:
x.min()

-0.7150000469272328

In [51]:
x.argmax()

1

In [52]:
x.argmin()

6

## indexs

In [54]:
z = np.arange(1,16)

In [55]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
z[3:8]

array([4, 5, 6, 7, 8])

In [59]:
z[3:8] = -5

In [60]:
z

array([ 1,  2,  3, -5, -5, -5, -5, -5,  9, 10, 11, 12, 13, 14, 15])

In [62]:
slicingZ = z[9:15]

In [63]:
slicingZ[:] = 1232442

In [64]:
z

array([      1,       2,       3,      -5,      -5,      -5,      -5,
            -5,       9, 1232442, 1232442, 1232442, 1232442, 1232442,
       1232442])

## matrix 

In [66]:
MyList = [[1,2,3] , [4,5,6] , [7,8,9]]

In [67]:
MyMatrix = np.array(MyList)

In [68]:
MyMatrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
MyMatrix[1][2]

6

In [70]:
MyMatrix[1,2]

6

In [76]:
MyMatrix[0: , 0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## operations

In [80]:
Sequence = np.random.randint(1,100,25)

In [81]:
Sequence

array([85, 14, 31, 71, 78, 49, 66, 13, 52, 30, 91, 30, 21, 65, 21, 86, 92,
       34, 33, 23, 37,  5, 90, 24, 20])

In [82]:
Result = Sequence > 50

In [84]:
Result

array([ True, False, False,  True,  True, False,  True, False,  True,
       False,  True, False, False,  True, False,  True,  True, False,
       False, False, False, False,  True, False, False])

In [85]:
Sequence[Result]

array([85, 71, 78, 66, 52, 91, 65, 86, 92, 90])